BEGIN;

INSERT INTO "story" ("name", "level", "description") VALUES
('L''histoire des 4 créateurs', 1, 'Dans cette histoire, tu vas explorer des îles mystérieuses, aller jusqu''au bout de l''univers, rencontrer robots, sirènes et pirates, et peut être même repousser une invasion extraterrestre !'),
('L''enquête de la pomme ensorcelée', 1, 'Une enquête pour les jeunes détectives en herbe ! Tu vas pouvoir découvrir de nouveaux châteaux et plein de personnages hauts en couleur !'),
('La quête de la liberté', 2, 'Aventurier, aventurière, cette quête est pour toi ! De forêt en village, du bateau pirate aux fonds marins, à travers des rencontres toutes plus loufoques les unes que les autres, c''est certain, tu ne vas pas t''ennuyer !'),
('Découvertes spatiales', 2, 'Salut à toi, jeune astronaute ! Embarque dans ton vaisseau et pars à la découverte de nouvelles planètes ! Tu pourrais bien faire quelques rencontres et découvertes inattendues...');

INSERT INTO "genre" ("label", "img") VALUES
('Aventure', 'aventure'),
('Enquête', 'enquete'),
('Science-fiction', 'science_fiction');

INSERT INTO "world" ("label", "img") VALUES
('Pirate', 'pirate'),
('Espace', 'espace'),
('Fantastique', 'fantastique');

INSERT INTO "place" ("label", "img") VALUES
('sur une île', 'ile'),
('sur un bateau', 'bateau'),
('dans la cabine du capitaine', 'cabine'),
('dans un village', 'village'),
('dans une forêt', 'foret'),
('dans l''espace', 'espace'),
('sur une planète rouge', 'planete_rouge'),
('sur une planète bleue', 'planete_bleue'),
('au château', 'chateau'),
('en mer', 'mer'),
('sous l''océan', 'fonds_marins'),
('au château de glace', 'chateau_hiver'),
('au château royal', 'chateau_manoir'),
('dans une forêt calme et verdoyante', 'foret_verte'),
('dans une forêt sombre et mystérieuse', 'foret_sombre'),
('dans un vaisseau spatial', 'vaisseau_exterieur'),
('dans la cabine d''un vaisseau', 'vaisseau_interieur'),
('sur un bateau pirate', 'bateau_pirate');


INSERT INTO "npc" ("label", "img") VALUES
('Captain Frimousse le pirate', 'pirate'),
('Maître-Poulpe', 'poulpe'),
('Irène la sirène', 'sirene'),
('Toto le robot', 'robot1'),
('Bérengère la sorcière', 'sorciere'),
('José le chevalier', 'chevalier'),
('Inès la princesse', 'princesse'),
('Jean-Requin', 'requin'),
('Hugo le robot', 'robot2'),
('Cléo la robot', 'robot3'),
('Théo le robot', 'robot4'),
('Léo le robot', 'robot5');

INSERT INTO "item" ("label", "img") VALUES
('Laser', 'laser'),
('Poisson', 'poisson'),
('Baguette Magique', 'baguette'),
('Pomme', 'pomme'),
('Epée', 'epee');

INSERT INTO "action" ("label", "class", "consequence", "img") VALUES
('aller tout droit', 'no_npc', null, 'tout_droit'),
('aller à droite', 'no_npc', null, 'a_droite'),
('parler', 'npc', '"Suis-moi"', 'parler'),
('explorer', 'no_npc', null, 'explorer'),
('faire une blague', 'npc', 'Elle est bien bonne ! Tu reprends ta route.', 'blague'),
('trouver le trésor', 'ending', 'Bravo, tu as trouvé le trésor ! Quelle aventure !', 'tresor'),
('rentrer chez soi pour manger du poisson', 'bonus_ending', 'Bravo, tu es rentré chez toi pour manger du poisson ! Quelle aventure !', 'rentrer_poisson'),
('voler', 'npc', 'C''est pas très gentil de voler...', 'voler'),
('boire du jus de poire', 'no_npc', 'Délicieux ce jus de poire ! Tu reprends ta route.', 'boire_jus'),
('nettoyer les écrous', 'npc', 'Quel boulot ! Tu reprends ta route.', 'nettoyer_ecrous'),
('repousser une invasion extraterrestre', 'bonus_ending', 'Bravo, tu as repoussé une invasion extraterrestre. Quelle aventure !', 'repousser_invasion'),
('rentrer chez soi et partir à la retraite', 'ending', 'Bravo, tu es rentré chez toi. Tu vas pouvoir profiter de ta retraite... Quelle aventure !', 'rentrer_retraite'),
('fuir', 'npc', null, 'fuir'),
('chanter', 'no_npc', 'Quelle voix ! Tu reprends ta route.', 'chanter'),
('manger son goûter', 'no_npc', 'Miam !', 'manger'),
('proposer un concours de déguisement', 'npc', null, 'deguisement'),
('continuer de vivre des aventures en voyageant à travers le monde', 'ending', 'Bravo, tu as décidé de vivre une vie faite de quêtes et de voyages... Quelle aventure !', 'voyager_aventure'),
('rendre Excalibur à la Dame du Lac', 'bonus_ending', 'Bravo, tu as décidé de rendre l''épée du roi Arthur à la Dame du Lac, et elle t''en remercie. Après tout, c''était d''abord son épée, à elle. Quelle aventure !', 'rendre_epee'),
('réaliser une chanson qui deviendra un tube médiéval', 'bonus_ending', 'Bravo, tu viens d''enregistrer ton premier single, et il cartonne dans toutes les auberges ! Quelle aventure !', 'tube_medieval'),
('rentrer chez soi, planter une pomme, et attendre que ce futur pommier donne des fruits', 'bonus_ending', 'Bravo, tu as décidé d''arrêter tes aventures pour retourner à ton jardin. On espère que la pomme que tu as planté deviendra un beau pommier... Quelle aventure !', 'jardiner'),
('demander gentiment son chemin', 'npc', null, 'demander_chemin'),
('se reposer', 'no_npc', null, 'se_reposer'),
('exercer ses talents de mécanicien', 'bonus_ending', 'Bravo, tu deviens le chef mécanicien du peuple robot !', 'mecanicien'),
('aller à la rencontre du peuple robot', 'bonus_ending', 'Bravo ! Tu enseignes l''art de la blague au peuple robot !', 'rencontre_robot'),
('aller à la rencontre des extraterrestres', 'bonus_ending', 'Bravo, tu cohabites en paix avec les extraterrestres ! Quelle aventure !', 'rencontre_extraterrestres'),
('se lier d''amitié avec un robot', 'bonus_ending', 'Bravo ! Tu as trouvé un compagnon robot pour de nouvelles explorations spatiales ! Quelle aventure !', 'amitie_robot'),
('faire l''inventaire de tes équipements', 'bonus_ending', 'Bravo ! Tu as des pièces pour entretenir ton vaisseau et continuer ton périple ! Quelle aventure !', 'inventaire_equipements'),
('fonder une civilisation sous-marine', 'bonus_ending', 'Bravo, tu découvres l''océan local et fonde une civilisation sous-marine ! Quelle aventure !', 'civilisation_marine'),
('explorer les mers', 'bonus_ending', 'Bravo, tu décides d''explorer les mers et les océans locaux ! Qui sait quelles découvertes t''attendent ?', 'explorer_mers'),
('regagner ton vaisseau', 'no_npc', null, 'regagner_vaisseau'),
('mettre le cap vers la Terre', 'bonus_ending', 'Bravo, tu as décidé de rentrer sur Terre pour partager tes grandes découvertes !', 'rentrer_terre'),
('construire un bateau', 'no_npc', null, 'construire_bateau'),
('aller à gauche', 'no_npc', null, 'a_gauche');

INSERT INTO "compartment" ("position", "class", "children", "story_id", "place_id", "npc_id") VALUES
(1, 'beginning', '2,3', 1, 1, null),
(2, 'middle', '4', 1, 1, 1),
(2, 'middle', '5,6', 1, 2, 3),
(3, 'middle', '7,8', 1, 3, 2),
(3, 'ending', null, 1, 3, null),
(3, 'middle', '9,10', 1, 6, 4),
(4, 'ending', null, 1, 4, null),
(4, 'bonus_ending', null, 1, 5, null),
(4, 'bonus_ending', null, 1, 7, null),
(4, 'ending', null, 1, 8, null),
(1, 'beginning', '12,13', 3, 5, 5),
(2, 'middle', '14,15', 3, 4, 7),
(2, 'middle', '16,17', 3, 9, 6),
(3, 'middle', '18,19', 3, 1, 1),
(3, 'middle', '19,20', 3, 10, 3),
(3, 'middle', '21,22', 3, 2, 2),
(3, 'middle', '23,28', 3, 4, 1),
(4, 'middle', '24,25', 3, 2, 8),
(4, 'middle', '25,26', 3, 3, 1),
(4, 'bonus_ending', null, 3, 11, null),
(4, 'middle', '27,28', 3, 10, 3),
(4, 'middle', '28,29', 3, 1, 2),
(4, 'ending', null, 3, 2, null),
(5, 'ending', null, 3, 1, null),
(5, 'bonus_ending', null, 3, 10, null),
(5, 'ending', null, 3, 2, null),
(5, 'ending', null, 3, 1, null),
(5, 'bonus_ending', null, 3, 3, null),
(5, 'ending', null, 3, 10, null),
(1, 'beginning', '31,32', 4, 17, null),
(2, 'middle', '33,34', 4, 16, null),
(2, 'middle', '35,36', 4, 6, null),
(3, 'middle', '37,38', 4, 7, 11),
(3, 'bonus_ending', null, 4, 7, null),
(3, 'middle', '39,40', 4, 6, 10),
(3, 'middle', '41, 42', 4, 8, null),
(4, 'bonus_ending', null, 4, 7, 9),
(4, 'bonus_ending', null, 4, 7, 4),
(4, 'bonus_ending', null, 4, 17, 10),
(4, 'bonus_ending', null, 4, 17, null),
(4, 'bonus_ending', null, 4, 11, null),
(4, 'middle', '43,44', 4, 10, null),
(5, 'bonus_ending', null, 4, 17, null),
(5, 'bonus_ending', null, 4, 10, null),
(1, 'beginning', '46,47', 2, 9, null),
(2, 'middle', '48,49', 2, 14, 6),
(2, 'middle', '50,51', 2, 15, 5),
(3, 'bonus_ending', null, 2, 14, null),
(3, 'middle', '52,53', 2, 13, 7),
(3, 'middle', '54', 2, 4, null),
(3, 'middle', '55,56', 2, 4, 5),
(4, 'middle', '57,58', 2, 13, 7),
(4, 'middle', '59', 2, 13, 7),
(4, 'ending', null, 2, 9, null),
(4, 'bonus_ending', null, 2, 15, 5),
(4, 'middle', '60', 2, 4, 5),
(5, 'middle', '61', 2, 5, null),
(5, 'middle', '62,63', 2, 15, 5),
(5, 'bonus_ending', null, 2, 9, null),
(5, 'bonus_ending', null, 2, 4, 5),
(6, 'ending', null, 2, 12, null),
(6, 'ending', null, 2, 15, null),
(6, 'ending', null, 2, 9, 5),
(5, 'ending', null, 3, 10, null);

INSERT INTO "action_has_item" ("action_id", "item_id") VALUES
(11, 1),
(7, 2),
(18, 5),
(19, 3),
(20, 4);

INSERT INTO "story_has_genre" ("story_id", "genre_id") VALUES
(1, 1),
(2, 2),
(3, 1),
(3, 2),
(4, 3);

INSERT INTO "compartment_has_action" ("compartment_id", "action_id", "child", "item") VALUES
(1, 1, 2, null),
(1, 2, 3, null),
(2, 3, 4, null),
(3, 8, 6, 1),
(3, 9, 5, null),
(4, 4, 7, null),
(4, 5, 8, 2),
(5, 6, null, null),
(6, 3, 10, null),
(6, 10, 9, null),
(7, 6, null, null),
(8, 7, null, null),
(9, 11, null, null),
(10, 12, null, null),
(11, 13, 13, 4),
(11, 21, 12, 3),
(12, 3, 14, 5),
(12, 4, 15, null),
(13, 8, 16, null),
(13, 14, 17, null),
(14, 5, 18, null),
(14, 9, 19, null),
(15, 3, 19, null),
(15, 14, 20, null),
(16, 15, 21, null),
(16, 16, 22, null),
(17, 1, 23, null),
(17, 13, 28, null),
(18, 1, 24, null),
(18, 2, 25, null),
(19, 1, 26, null),
(19, 3, 25, null),
(20, 19, null, null),
(21, 1, 27, null),
(21, 13, 28, null),
(22, 4, 29, null),
(22, 5, 28, null),
(23, 17, null, null),
(24, 17, null, null),
(25, 18, null, null),
(26, 17, null, null),
(27, 12, null, null),
(28, 20, null, null),
(29, 17, null, null),
(30, 1, 31, null),
(30, 2, 32, null),
(31, 4, 34, null),
(31, 22, 33, null),
(32, 4, 36, null),
(32, 22, 35, null),
(33, 5, 38, null),
(33, 10, 37, null),
(34, 11, null, null),
(34, 25, null, null),
(35, 3, 39, null),
(35, 8, 40, null),
(36, 1, 41, null),
(36, 2, 42, null),
(37, 23, null, null),
(38, 24, null, null),
(39, 26, null, null),
(40, 27, null, null),
(41, 28, null, null),
(42, 30, 43, null),
(42, 32, 44, null),
(43, 31, null, null),
(44, 29, null, null),
(45, 2, 47, null),
(45, 33, 46, null),
(46, 3, 49, null),
(46, 16, 48, 5),
(47, 3, 51, 3),
(47, 13, 50, null),
(48, 18, null, null),
(49, 8, 53, 4),
(49, 15, 52, null),
(50, 9, 54, null),
(51, 5, 55, 2),
(51, 9, 56, null),
(52, 13, 58, null),
(52, 14, 57, null),
(53, 13, 59, null),
(54, 12, null, null),
(55, 7, null, null),
(56, 14, 60, null),
(57, 4, 61, null),
(58, 3, 63, null),
(58, 4, 62, null),
(59, 20, null, null),
(60, 19, null, null),
(61, 17, null, null),
(62, 6, null, null),
(63, 12, null, null);

INSERT INTO "place_has_world" ("place_id", "world_id") VALUES
(1, 1),
(2, 1),
(3, 1),
(4, 3),
(5, 3),
(6, 2),
(7, 2),
(8, 2),
(9, 3),
(10, 1),
(10, 3),
(11, 1),
(12, 3),
(13, 3),
(14, 3),
(15, 3),
(16, 2),
(17, 2),
(18, 1);

INSERT INTO "npc_has_world" ("npc_id", "world_id") VALUES
(1, 1),
(2, 1),
(3, 1),
(3, 3),
(4, 2),
(5, 3),
(6, 3),
(7, 3),
(8, 1),
(9, 2),
(10, 2),
(11, 2),
(12, 2);

INSERT INTO "npc_has_action" ("npc_id", "action_id") VALUES
(4, 10);

COMMIT;